apiVersion: external-secrets.io/v1
kind: SecretStore
metadata: {name: projecty-secrets, namespace: projecty}
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-reader
