apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - aws-secret-store.yaml
patches:
  - path: production-shape.yaml
  - path: ingress-acm.yaml
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: projecty
