apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - aws-secret-store.yaml
  - strimzi-kafka.yaml
patches:
  - path: production-shape.yaml
  - path: remove-base-kafka.yaml
  - path: strimzi-kafka-alias.yaml
  - path: ingress-acm.yaml
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: projecty
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/envFrom/-
        value:
          configMapRef:
            name: projecty-cloud-runtime
    target:
      group: apps
      version: v1
      kind: Deployment
      name: (api-gateway|identity|rental-core|billing|risk-pricing|telemetry|console)
