apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: projecty-unsigned-canary
spec:
  background: false
  webhookConfiguration:
    failurePolicy: Fail
    timeoutSeconds: 30
  rules:
    - name: reject-unsigned-canary
      match:
        any:
          - resources:
              kinds: [Pod]
              names: [projecty-unsigned-canary]
              namespaces: [projecty]
      verifyImages:
        - imageReferences: [ghcr.io/kyverno/test-verify-image:unsigned]
          failureAction: Enforce
          mutateDigest: false
          required: true
          verifyDigest: false
          cosignOCI11: true
          attestors:
            - count: 1
              entries:
                - keyless:
                    subject: https://github.com/iVega123/ProjectY/.github/workflows/ci.yml@refs/heads/main
                    issuer: https://token.actions.githubusercontent.com
                    rekor:
                      url: https://rekor.sigstore.dev
