apiVersion: v1
kind: ServiceAccount
metadata: {name: api-gateway}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata: {name: identity}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata: {name: rental-core}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata: {name: media-guard}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata: {name: billing}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata: {name: risk-pricing}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata: {name: telemetry}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata: {name: console}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata: {name: cockroachdb}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata: {name: redis}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata: {name: rabbitmq}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata: {name: minio}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata: {name: kafka}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata: {name: cassandra}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata: {name: schema-registry}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata: {name: cockroach-schema}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata: {name: kafka-topics}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata: {name: cassandra-schema}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata: {name: schema-contracts}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata: {name: external-secrets-reader}
automountServiceAccountToken: false
