// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.31.1
// source: rider.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RiderEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       *string                `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3,oneof" json:"event_id,omitempty"`
	RiderId       *string                `protobuf:"bytes,2,opt,name=rider_id,json=riderId,proto3,oneof" json:"rider_id,omitempty"`
	OccurredAtMs  *int64                 `protobuf:"varint,3,opt,name=occurred_at_ms,json=occurredAtMs,proto3,oneof" json:"occurred_at_ms,omitempty"`
	ObjectKey     *string                `protobuf:"bytes,4,opt,name=object_key,json=objectKey,proto3,oneof" json:"object_key,omitempty"`
	CnhNumber     *string                `protobuf:"bytes,5,opt,name=cnh_number,json=cnhNumber,proto3,oneof" json:"cnh_number,omitempty"`
	Verified      *bool                  `protobuf:"varint,6,opt,name=verified,proto3,oneof" json:"verified,omitempty"`
	RiskScore     *int32                 `protobuf:"varint,7,opt,name=risk_score,json=riskScore,proto3,oneof" json:"risk_score,omitempty"`
	PricingJson   *string                `protobuf:"bytes,8,opt,name=pricing_json,json=pricingJson,proto3,oneof" json:"pricing_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiderEvent) Reset() {
	*x = RiderEvent{}
	mi := &file_rider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiderEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiderEvent) ProtoMessage() {}

func (x *RiderEvent) ProtoReflect() protoreflect.Message {
	mi := &file_rider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiderEvent.ProtoReflect.Descriptor instead.
func (*RiderEvent) Descriptor() ([]byte, []int) {
	return file_rider_proto_rawDescGZIP(), []int{0}
}

func (x *RiderEvent) GetEventId() string {
	if x != nil && x.EventId != nil {
		return *x.EventId
	}
	return ""
}

func (x *RiderEvent) GetRiderId() string {
	if x != nil && x.RiderId != nil {
		return *x.RiderId
	}
	return ""
}

func (x *RiderEvent) GetOccurredAtMs() int64 {
	if x != nil && x.OccurredAtMs != nil {
		return *x.OccurredAtMs
	}
	return 0
}

func (x *RiderEvent) GetObjectKey() string {
	if x != nil && x.ObjectKey != nil {
		return *x.ObjectKey
	}
	return ""
}

func (x *RiderEvent) GetCnhNumber() string {
	if x != nil && x.CnhNumber != nil {
		return *x.CnhNumber
	}
	return ""
}

func (x *RiderEvent) GetVerified() bool {
	if x != nil && x.Verified != nil {
		return *x.Verified
	}
	return false
}

func (x *RiderEvent) GetRiskScore() int32 {
	if x != nil && x.RiskScore != nil {
		return *x.RiskScore
	}
	return 0
}

func (x *RiderEvent) GetPricingJson() string {
	if x != nil && x.PricingJson != nil {
		return *x.PricingJson
	}
	return ""
}

var File_rider_proto protoreflect.FileDescriptor

const file_rider_proto_rawDesc = "" +
	"\n" +
	"\vrider.proto\x12\x10project_y.events\"\xa4\x03\n" +
	"\n" +
	"RiderEvent\x12\x1e\n" +
	"\bevent_id\x18\x01 \x01(\tH\x00R\aeventId\x88\x01\x01\x12\x1e\n" +
	"\brider_id\x18\x02 \x01(\tH\x01R\ariderId\x88\x01\x01\x12)\n" +
	"\x0eoccurred_at_ms\x18\x03 \x01(\x03H\x02R\foccurredAtMs\x88\x01\x01\x12\"\n" +
	"\n" +
	"object_key\x18\x04 \x01(\tH\x03R\tobjectKey\x88\x01\x01\x12\"\n" +
	"\n" +
	"cnh_number\x18\x05 \x01(\tH\x04R\tcnhNumber\x88\x01\x01\x12\x1f\n" +
	"\bverified\x18\x06 \x01(\bH\x05R\bverified\x88\x01\x01\x12\"\n" +
	"\n" +
	"risk_score\x18\a \x01(\x05H\x06R\triskScore\x88\x01\x01\x12&\n" +
	"\fpricing_json\x18\b \x01(\tH\aR\vpricingJson\x88\x01\x01B\v\n" +
	"\t_event_idB\v\n" +
	"\t_rider_idB\x11\n" +
	"\x0f_occurred_at_msB\r\n" +
	"\v_object_keyB\r\n" +
	"\v_cnh_numberB\v\n" +
	"\t_verifiedB\r\n" +
	"\v_risk_scoreB\x0f\n" +
	"\r_pricing_jsonb\x06proto3"

var (
	file_rider_proto_rawDescOnce sync.Once
	file_rider_proto_rawDescData []byte
)

func file_rider_proto_rawDescGZIP() []byte {
	file_rider_proto_rawDescOnce.Do(func() {
		file_rider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rider_proto_rawDesc), len(file_rider_proto_rawDesc)))
	})
	return file_rider_proto_rawDescData
}

var file_rider_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_rider_proto_goTypes = []any{
	(*RiderEvent)(nil), // 0: project_y.events.RiderEvent
}
var file_rider_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rider_proto_init() }
func file_rider_proto_init() {
	if File_rider_proto != nil {
		return
	}
	file_rider_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rider_proto_rawDesc), len(file_rider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rider_proto_goTypes,
		DependencyIndexes: file_rider_proto_depIdxs,
		MessageInfos:      file_rider_proto_msgTypes,
	}.Build()
	File_rider_proto = out.File
	file_rider_proto_goTypes = nil
	file_rider_proto_depIdxs = nil
}
