// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.31.1
// source: rider_v2.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Versioned successor of rider.proto, carried on rider.verified.v2.
//
// Apicurio's FULL check rejects adding a field to a governed schema: its
// forward pass reverses the schemas and reads the new field as an unreserved
// removal. Rather than downgrade FULL or ignore its verdict, the evolved fact
// gets its own subject, which has no prior version to be incompatible with.
//
// Field numbers match rider.proto exactly, so a v1 decoder reads a v2 payload
// and skips field 9 as unknown. That is what makes the rollout cheap: the
// producer writes both topics, consumers move one at a time, v1 retires last.
type RiderEventV2 struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	EventId      *string                `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3,oneof" json:"event_id,omitempty"`
	RiderId      *string                `protobuf:"bytes,2,opt,name=rider_id,json=riderId,proto3,oneof" json:"rider_id,omitempty"`
	OccurredAtMs *int64                 `protobuf:"varint,3,opt,name=occurred_at_ms,json=occurredAtMs,proto3,oneof" json:"occurred_at_ms,omitempty"`
	ObjectKey    *string                `protobuf:"bytes,4,opt,name=object_key,json=objectKey,proto3,oneof" json:"object_key,omitempty"`
	CnhNumber    *string                `protobuf:"bytes,5,opt,name=cnh_number,json=cnhNumber,proto3,oneof" json:"cnh_number,omitempty"`
	Verified     *bool                  `protobuf:"varint,6,opt,name=verified,proto3,oneof" json:"verified,omitempty"`
	RiskScore    *int32                 `protobuf:"varint,7,opt,name=risk_score,json=riskScore,proto3,oneof" json:"risk_score,omitempty"`
	PricingJson  *string                `protobuf:"bytes,8,opt,name=pricing_json,json=pricingJson,proto3,oneof" json:"pricing_json,omitempty"`
	// rental-core does not own the rider's name. It holds it so rental.closed
	// can describe the fact without calling identity while assembling the event.
	Name          *string `protobuf:"bytes,9,opt,name=name,proto3,oneof" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiderEventV2) Reset() {
	*x = RiderEventV2{}
	mi := &file_rider_v2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiderEventV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiderEventV2) ProtoMessage() {}

func (x *RiderEventV2) ProtoReflect() protoreflect.Message {
	mi := &file_rider_v2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiderEventV2.ProtoReflect.Descriptor instead.
func (*RiderEventV2) Descriptor() ([]byte, []int) {
	return file_rider_v2_proto_rawDescGZIP(), []int{0}
}

func (x *RiderEventV2) GetEventId() string {
	if x != nil && x.EventId != nil {
		return *x.EventId
	}
	return ""
}

func (x *RiderEventV2) GetRiderId() string {
	if x != nil && x.RiderId != nil {
		return *x.RiderId
	}
	return ""
}

func (x *RiderEventV2) GetOccurredAtMs() int64 {
	if x != nil && x.OccurredAtMs != nil {
		return *x.OccurredAtMs
	}
	return 0
}

func (x *RiderEventV2) GetObjectKey() string {
	if x != nil && x.ObjectKey != nil {
		return *x.ObjectKey
	}
	return ""
}

func (x *RiderEventV2) GetCnhNumber() string {
	if x != nil && x.CnhNumber != nil {
		return *x.CnhNumber
	}
	return ""
}

func (x *RiderEventV2) GetVerified() bool {
	if x != nil && x.Verified != nil {
		return *x.Verified
	}
	return false
}

func (x *RiderEventV2) GetRiskScore() int32 {
	if x != nil && x.RiskScore != nil {
		return *x.RiskScore
	}
	return 0
}

func (x *RiderEventV2) GetPricingJson() string {
	if x != nil && x.PricingJson != nil {
		return *x.PricingJson
	}
	return ""
}

func (x *RiderEventV2) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

var File_rider_v2_proto protoreflect.FileDescriptor

const file_rider_v2_proto_rawDesc = "" +
	"\n" +
	"\x0erider_v2.proto\x12\x10project_y.events\"\xc8\x03\n" +
	"\fRiderEventV2\x12\x1e\n" +
	"\bevent_id\x18\x01 \x01(\tH\x00R\aeventId\x88\x01\x01\x12\x1e\n" +
	"\brider_id\x18\x02 \x01(\tH\x01R\ariderId\x88\x01\x01\x12)\n" +
	"\x0eoccurred_at_ms\x18\x03 \x01(\x03H\x02R\foccurredAtMs\x88\x01\x01\x12\"\n" +
	"\n" +
	"object_key\x18\x04 \x01(\tH\x03R\tobjectKey\x88\x01\x01\x12\"\n" +
	"\n" +
	"cnh_number\x18\x05 \x01(\tH\x04R\tcnhNumber\x88\x01\x01\x12\x1f\n" +
	"\bverified\x18\x06 \x01(\bH\x05R\bverified\x88\x01\x01\x12\"\n" +
	"\n" +
	"risk_score\x18\a \x01(\x05H\x06R\triskScore\x88\x01\x01\x12&\n" +
	"\fpricing_json\x18\b \x01(\tH\aR\vpricingJson\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\t \x01(\tH\bR\x04name\x88\x01\x01B\v\n" +
	"\t_event_idB\v\n" +
	"\t_rider_idB\x11\n" +
	"\x0f_occurred_at_msB\r\n" +
	"\v_object_keyB\r\n" +
	"\v_cnh_numberB\v\n" +
	"\t_verifiedB\r\n" +
	"\v_risk_scoreB\x0f\n" +
	"\r_pricing_jsonB\a\n" +
	"\x05_nameb\x06proto3"

var (
	file_rider_v2_proto_rawDescOnce sync.Once
	file_rider_v2_proto_rawDescData []byte
)

func file_rider_v2_proto_rawDescGZIP() []byte {
	file_rider_v2_proto_rawDescOnce.Do(func() {
		file_rider_v2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rider_v2_proto_rawDesc), len(file_rider_v2_proto_rawDesc)))
	})
	return file_rider_v2_proto_rawDescData
}

var file_rider_v2_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_rider_v2_proto_goTypes = []any{
	(*RiderEventV2)(nil), // 0: project_y.events.RiderEventV2
}
var file_rider_v2_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rider_v2_proto_init() }
func file_rider_v2_proto_init() {
	if File_rider_v2_proto != nil {
		return
	}
	file_rider_v2_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rider_v2_proto_rawDesc), len(file_rider_v2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rider_v2_proto_goTypes,
		DependencyIndexes: file_rider_v2_proto_depIdxs,
		MessageInfos:      file_rider_v2_proto_msgTypes,
	}.Build()
	File_rider_v2_proto = out.File
	file_rider_v2_proto_goTypes = nil
	file_rider_v2_proto_depIdxs = nil
}
